# Test on local, build for embedded on NRF52

[tasks.cbindgen]
command = "cbindgen"
args = ["--config", "cbindgen.toml", "--crate", "logz-example-rs", "--output", "include/generated/liblogz_example_rs.h"]

[tasks.build-nrf52]
command = "cargo"
toolchain = "nightly"
args = ["build", "--lib", "--target", "thumbv7em-none-eabihf", "--release", "--verbose"] 
dependencies = ["cbindgen"]

[tasks.build-nrf53]
command = "cargo"
toolchain = "nightly"
args = ["build", "--lib", "--target", "thumbv8m.main-none-eabihf", "--release", "--verbose"]
dependencies = ["cbindgen"]

[tasks.build]
command = "cargo"
toolchain = "nightly"
args = ["build"]
dependencies = ["build-nrf52", "build-nrf53"]

[tasks.test-release]
command = "cargo"
toolchain = "nightly"
args = ["test", "--lib", "--release"]
dependencies = ["build"]

[tasks.test]
command = "cargo"
toolchain = "nightly"
args = ["test", "--lib"]
dependencies = ["test-release"]